module HTTPX
  module Plugins
    module Auth
      type auth_header_value_type = String | ^(Request request) -> string

      interface _AuthOptions
        def auth_header_value: () -> auth_header_value_type?

        def auth_header_type: () -> String?
      end

      module InstanceMethods
        @auth_header_value: String
        @skip_auth_header_value: bool

        def authorization: (?string token, ?auth_header_type: string) ?{ (Request) -> string } -> instance

        def bearer_auth: (?string token) ?{ (Request) -> string } -> instance

        def skip_auth_header: [T] { () -> T } -> T

        def reset_auth_header_value!: () -> void

        private

        def generate_auth_token: () -> String?

        def dynamic_auth_token?: (auth_header_value_type auth_header_value) -> boolish
      end

      module RequestMethods
        @auth_token_value: String?

        def authorized?: () -> bool

        def unauthorize!: () -> void

        def authorize: (String auth_value) -> void
      end

      module AuthRetries
        module InstanceMethods
          private

          def auth_error?: (response response, Options options) -> boolish
        end
      end
    end

    type sessionAuth = Session & Auth::InstanceMethods
  end
end
