module HTTPX
  module Plugins
    module AwsSdkAuthentication
      class Configuration
        attr_reader profile: String?

        private

        def initialize: (String? profile) -> void
      end

      class Credentials
        @aws_credentials: untyped

        include _SigV4Credentials

        private

        def initialize: (untyped aws_credentials) -> untyped
      end

      interface _AwsSdkOptions
        def aws_profile: () -> String?
      end

      def self.load_dependencies: (singleton(Session)) -> void

      def self.configure: (singleton(Session)) -> void

      def self.extra_options: (Options) -> (Options & _AwsSdkOptions)

      def self.credentials: (String? profile) -> Credentials

      def self.region: (String? profile) -> String

      module InstanceMethods
        def aws_sdk_authentication: (?credentials: Credentials, ?region: String, **untyped) -> instance
      end
    end

    type sessionAwsSdkAuthentication = awsSigV4Session & AwsSdkAuthentication::InstanceMethods
  end
end