module HTTPX
  module Plugins
    module BasicAuth
      def self.load_dependencies: (singleton(Session) klass) -> void

      def self.configure: (singleton(Session) klass) -> void

      module InstanceMethods
        def basic_auth: (string user, string password) -> instance
      end
    end

    type sessionBasicAuth = sessionAuth & BasicAuth::InstanceMethods
  end
end
