module HTTPX
  module Plugins
    module BasicAuth
      def self.load_dependencies: (singleton(Session)) -> void

      def self.configure: (singleton(Session)) -> void

      module InstanceMethods
        def basic_authentication: (string user, string password) -> instance
      end
    end

    type sessionBasicAuth = sessionAuthentication & Authentication::InstanceMethods & BasicAuth::InstanceMethods
  end
end
