module HTTPX
  module Plugins
    module Cookies
      type jar = Jar | _Each[cookies]

      interface _CookieOptions
        def cookies: () -> Jar?
        def cookies=: (jar) -> Jar
        def with_cookies: (jar) -> instance
      end
 
      def self.extra_options: (Options) -> (Options & _CookieOptions)

      module InstanceMethods
        def cookies: () -> Jar
      end

      module HeadersMethods
        def set_cookie: (Array[Cookie]) -> void
      end
    end

    type sessionCookies = Session & Plugins::Cookies::InstanceMethods
    type headersCookies = Headers & Plugins::Cookies::HeadersMethods
  end
end
