module HTTPX
  module Plugins
    module DigestAuth
      DigestError: singleton(Error)

      interface _DigestOptions
        def digest: () -> Authentication::Digest?
      end

      def self.extra_options: (Options) -> (Options & _DigestOptions)

      def self.load_dependencies: (*untyped) -> void

      module InstanceMethods
        def digest_authentication: (string user, string password) -> instance
      end
    end

    type sessionDigestAuth = sessionAuthentication & DigestAuth::InstanceMethods
  end
end
