module HTTPX
  module Plugins
    module DigestAuth
      interface _DigestOptions
        def digest: () -> Authentication::Digest?
      end

      def self.extra_options: (Options) -> (Options & _DigestOptions)

      def self.load_dependencies: (singleton(Session) klass) -> void

      module InstanceMethods
        def digest_auth: (string user, string password, ?hashed: bool) -> instance
      end
    end

    type sessionDigestAuth = sessionAuth & DigestAuth::InstanceMethods
  end
end
