module HTTPX
  module Plugins
    module Expect
      EXPECT_TIMEOUT: Integer

      interface _ExpectOptions
        def expect_timeout: () -> Integer?

        def expect_threshold_size: () -> Integer?
      end

      def self.extra_options: (Options) -> (Options & _ExpectOptions)
    end
  end
end
