module HTTPX
  module Plugins
    module H2C
      VALID_H2C_VERBS: Array[verb]

      def self.load_dependencies: (*untyped) -> void
      def self.configure: (singleton(Session)) -> void
      def self.call: (Connection, Request, response) -> void

      interface _H2COptions
        def h2c_class: () -> (singleton(Connection::HTTP2) & H2CParser)
      end

      module H2CParser
        def upgrade: (Request, Response) -> void
      end

      module RequestMethods
        def valid_h2c_verb?: () -> bool
      end

      module ConnectionMethods
        def upgrade_to_h2c: (Request, Response) -> void
      end
    end
  end
end
