module HTTPX
  module Plugins
    module H2C
      VALID_H2C_VERBS: Array[Symbol]

      def self.load_dependencies: (singleton(Session)) -> void
      def self.configure: (*untyped) -> void
      def self.call: (Connection, Request, response) -> void

      class H2CParser < Connection::HTTP2
        def upgrade: (Request, Response) -> void
      end

      module ConnectionMethods
        def upgrade_to_h2c: (Request, Response) -> void
      end
    end

    type sessionH2C = Session & Plugins::H2C::InstanceMethods
  end
end
