module HTTPX
  module Plugins
    module H2C
      # def self.load_dependencies: (singleton(Session)) -> void
      
      module InstanceMethods
        VALID_H2C_METHODS: Array[Symbol]
        
        private

        def valid_h2c_upgrade_request: (Request) -> bool
        def valid_h2c_upgrade?: (Request, Response, Options) -> bool
      end

      class H2CParser < Connection::HTTP2
        def upgrade: (Request, Response) -> void
      end

      module ConnectionMethods
        def upgrade: (Request, Response) -> void
      end
    end

    type sessionH2C = Session & Plugins::H2C::InstanceMethods
  end
end
