module HTTPX
  module Plugins
    module NTLMAuthentication

      interface _NTLMOptions
        def ntlm: () -> NTLMParams?
        def ntlm=: (NTLMParams) -> NTLMParams
      end
 
      def self.extra_options: (Options) -> (Options & _NTLMOptions)

      def self.load_dependencies: (*untyped) -> void

      module InstanceMethods
        def ntlm_authentication: (string user, string password, ?string? domain) -> instance
      end

      class NTLMParams
        attr_reader user: String
        attr_reader password: String
        attr_reader domain: String?
      end
    end

    type sessionNTLMAuthentication = sessionAuthentication & NTLMAuthentication::InstanceMethods
  end
end
