module HTTPX
  module Plugins
    module Persistent
      SAFE_REONNECTABLE_ERRORS: Array[singleton(StandardError)]

      def self.load_dependencies: (singleton(Session)) -> void

      def self.extra_options: (Options) -> (Options)

      module InstanceMethods
        private

        def reconnectable_error?: (StandardError error) -> bool

        def safe_reconnectable_error?: (StandardError error) -> bool
      end
    end

    type sessionPersistent = sessionFiberConcurrency & Persistent::InstanceMethods
  end
end
