module HTTPX
  module Plugins
    module Persistent
      def self.load_dependencies: (singleton(Session)) -> void

      def self.extra_options: (Options) -> (Options)

      module InstanceMethods
      end
    end

    type sessionPersistent = sessionFiberConcurrency & Persistent::InstanceMethods
  end
end
