module HTTPX
  module Plugins
    module RateLimiter
      RATE_LIMIT_CODES: Array[Integer]

      def self.load_dependencies: (singleton(Session)) -> void

      def self.retry_after_rate_limit: (untyped, response) -> Numeric?

      module InstanceMethods
        def rate_limit_error?: (response response) -> bool
      end
    end
  end
end