module HTTPX
  module Plugins
    module Upgrade
      type handlers_registry = Registry[Symbol, Class]

      def self.configure: (singleton(Session)) -> void

      interface _UpgradeOptions
        def upgrade_handlers: () -> handlers_registry?
      end

      def self.extra_options: (Options) -> (Options & _UpgradeOptions)

      module ConnectionMethods
        attr_reader upgrade_protocol: Symbol?
        attr_reader hijacked: boolish

        def hijack_io: () -> void
      end
    end
  end
end
