inherit_from: .rubocop-2.3.yml

Style/OptionalBooleanParameter:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'lib/httpx/io/unix.rb'

Style/HashTransformValues:
  Exclude:
    - 'lib/httpx/plugins/digest_authentication.rb'

Bundler/DuplicatedGem:
  Enabled: false

Naming/VariableNumber:
  Enabled: false