inherit_from: .rubocop.yml

# Because this cop doesn't work well with frozen regexes
Style/RedundantFreeze:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/AndOr:
  Enabled: False

Naming/UncommunicativeMethodParamName:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'test/resolver/native_test.rb'
  Max: 140

Lint/UnneededCopDisableDirective:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false
