version: '3'
services:
  httpx:
    environment:
      - SSL_CERT_FILE=/home/test/support/ci/certs/ca-bundle.crt
      - HTTPBIN_HOST=nghttp2
      - HTTPX_HTTP_PROXY=http://httpproxy:3128
      - HTTPX_HTTPS_PROXY=http://httpproxy:3128
      - HTTPX_SOCKS4_PROXY=socks4://socksproxy:8080
      - HTTPX_SOCKS4A_PROXY=socks4a://socksproxy:8080
      - HTTPX_SOCKS5_PROXY=socks5://socksproxy:8080
      - HTTPX_SSH_PROXY=ssh://sshproxy:22
      - PARALLEL=1
      - CI=1
      - JEKYLL_ENV=production
      - GEM_HOME=/usr/local/bundle
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_SILENCE_ROOT_WARNING=1
      - BUNDLE_APP_CONFIG=/usr/local/bundle
    image: ruby:alpine
    depends_on:
      - httpproxy 
      - socksproxy 
      - sshproxy
      - nghttp2
    volumes:
      - ./:/home
    entrypoint:
      /home/test/support/ci/build.sh
    links:
      - "nghttp2:another"

  sshproxy:
    image: registry.gitlab.com/honeyryderchuck/httpx/sshproxy:latest
    volumes:
      - ./test/support/ssh:/config
    depends_on:
      - nghttp2

  socksproxy:
    image: qautomatron/docker-3proxy
    volumes:
      - ./test/support/ci:/etc/3proxy

  httpproxy:
    image: sameersbn/squid:3.3.8-23

  nghttp2:
    image: registry.gitlab.com/honeyryderchuck/httpx/nghttp2:latest
    depends_on:
      - httpbin
          
  httpbin:
    image: citizenstig/httpbin
