version: '3'
services:
  httpx:
    environment:
      - PARALLEL=1
      - CI=1
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - squid
      - dante 
    command:
      "rake test"
  
      #  box:
      #    image: busybox
      #    volumes:
      #      - /box

  dante:
    image: vimagick/dante
    ports:
      - "1080:1080"
    networks:
      httpx:
        aliases:
          - dante 

  squid:
    image: sameersbn/squid:3.3.8-23
    ports:
      - "3128:3128"
    networks:
      httpx:
        aliases:
          - squid

networks:
  httpx:
    external:
      name: httpx 
volumes:
  box:
