version: '3'
services:
  httpx:
    environment:
      - SSL_CERT_FILE=/httpx/test/support/ci/certs/ca-bundle.crt
      - HTTPBIN_HOST=nghttp2:3001
      - HTTPBINS_HOST=nghttp2:3000
      - PARALLEL=1
      - CI=1
    build:
      context: .
      dockerfile: test/support/ci/Dockerfile 
    depends_on:
      - squid
      - dante
      - nghttp2
    volumes:
      - ./lib:/httpx/lib
      - ./test:/httpx/test
    command:
      "rake test"
  
      #  box:
      #    image: busybox
      #    volumes:
      #      - /box

  dante:
    image: vimagick/dante
    ports:
      - "1080:1080"

  squid:
    image: sameersbn/squid:3.3.8-23
    ports:
      - "3128:3128"

  nghttp2:
    image: dajobe/nghttpx
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - httpbin
    entrypoint:
      "/usr/bin/nghttpx"
    volumes:
      - ./test/support/ci:/home
    command:
      --conf /home/nghttp.conf --no-ocsp
      #--accesslog-file /dev/stdout errorlog-file /dev/stdout --dh-param-file /home/dhparam.pem --backend 'httpbin,8000' --frontend '0.0.0.0,3001;no-tls' --frontend '0.0.0.0,3000' /home/server.key /home/server.crt
          
  httpbin:
    image: citizenstig/httpbin
    ports:
      - 8000:8000
