version: '3'
services:
  httpx:
    environment:
      - SSL_CERT_FILE=/home/test/support/ci/certs/ca-bundle.crt
      - HTTPBIN_HOST=nghttp2
      - HTTPX_HTTP_PROXY=http://httpproxy:3128
      - HTTPX_HTTPS_PROXY=http://httpproxy:3128
      - HTTPX_SOCKS4_PROXY=socks4://socksproxy:8080
      - HTTPX_SOCKS4A_PROXY=socks4a://socksproxy:8080
      - HTTPX_SOCKS5_PROXY=socks5://socksproxy:8080
      - HTTPX_SSH_PROXY=ssh://sshproxy:22
      - PARALLEL=1
      - N=6 # minitest workers
      - MT_CPU=6 # minitest workers
      - CI=1
      - JEKYLL_ENV=production
      - GEM_HOME=/usr/local/bundle
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_SILENCE_ROOT_WARNING=1
      - BUNDLE_APP_CONFIG=/usr/local/bundle
    image: ruby:alpine
    depends_on:
      - httpproxy 
      - socksproxy 
      - sshproxy
      - nghttp2
    volumes:
      - ./:/home
    entrypoint:
      /home/test/support/ci/build.sh
    links:
      - "nghttp2:another"

  sshproxy:
    build:
      context: .
      dockerfile: ./test/support/ssh/Dockerfile
    volumes:
      - ./test/support/ssh:/config
    depends_on:
      - nghttp2

  socksproxy:
    image: qautomatron/docker-3proxy
    ports:
      - "8080:8080"
      - "3129:3129"
    volumes:
      - ./test/support/ci:/etc/3proxy

  httpproxy:
    image: sameersbn/squid:3.3.8-23
    ports:
      - "3128:3128"

  nghttp2:
    image: registry.gitlab.com/honeyryderchuck/httpx/nghttp2:2
    ports:
      - 80:80
      - 443:443
    depends_on:
      - httpbin
    entrypoint:
      /usr/local/bin/nghttpx
    volumes:
      - ./test/support/ci:/home
    command:
      --conf /home/nghttp.conf --no-ocsp
          
  httpbin:
    environment:
      - DEBUG=True
    image: citizenstig/httpbin
    command:
      gunicorn --bind=0.0.0.0:8000 --workers=6 --access-logfile - --error-logfile - --log-level debug --capture-output httpbin:app
