version: '3'
services:
  httpx:
    environment:
      - SSL_CERT_FILE=/httpx/test/support/ci/certs/ca-bundle.crt
      - HTTPBIN_HOST=nghttp2
      - PARALLEL=1
      - CI=1
    build:
      context: .
      dockerfile: test/support/ci/Dockerfile 
    depends_on:
      - squid
      - dante
      - nghttp2
    volumes:
      - ./lib:/httpx/lib
      - ./test:/httpx/test
    command:
      "rake test"
  
      #  box:
      #    image: busybox
      #    volumes:
      #      - /box

  dante:
    image: vimagick/dante
    ports:
      - "1080:1080"

  squid:
    image: sameersbn/squid:3.3.8-23
    ports:
      - "3128:3128"

  nghttp2:
    build:
      context: .
      dockerfile: test/support/ci/Dockerfile.nghttp2
    ports:
      - 80:80
      - 443:443
    depends_on:
      - httpbin
    entrypoint:
      /usr/local/bin/nghttpx
    volumes:
      - ./test/support/ci:/home
    command:
      --conf /home/nghttp.conf --no-ocsp
          
  httpbin:
    image: citizenstig/httpbin
    ports:
      - 8000:8000
