module HTTPX
  module Plugins::Cookies
    class Jar
      type cookie = Cookie | Array[[String, String, cookie_attributes]] | Array[[String, String]] | cookie_attributes

      include Enumerable[Cookie]

      @cookies: Array[Cookie]

      def parse: (String) -> void

      def add: (Cookie) -> void
             | (Cookie, String) -> void

      def []: (uri) -> Array[Cookie]

      def each: (uri) { (Cookie) -> void } -> void
              | (uri) -> Enumerable[Cookie]
              | () { (Cookie) -> void } -> void
              | () -> Enumerable[Cookie]
      private

      def initialize: () -> void
                    | (_Each[cookie]) -> untyped
    end
  end
end