module HTTPX
  Socks5Error: singleton(Error)

  module Plugins
    module Proxy
      module Socks5
        VERSION: Integer

        module ConnectionMethods
          def __socks5_proxy_connect: () ->  void
          def __socks5_on_packet: (String packet) ->  void
          def __socks5_check_version: (int) -> void
          def __on_socks5_error: (string) -> void
        end

        class SocksParser
          include Callbacks

          def close: () -> void
          def consume: (*untyped) -> void
          def empty: () -> bool
          def <<: (string) -> void

          private

          def initialize: (Buffer buffer, Options) -> untyped
        end

        module Packet
          def self?.negotiate: (Parameters) -> String
          def self?.authenticate: (Parameters) -> String
          def self?.connect: (uri) -> String
        end
      end
    end
  end
end
