module HTTPX
  class Socks4Error < ProxyError
  end

  module Plugins
    module Proxy
      module Socks4

        module ConnectionMethods
          def __socks4_proxy_connect: () ->  void
          def __socks4_on_packet: (String packet) ->  void
          def on_socks4_error: (string) -> void
        end

        class SocksParser
          include HTTPX::Callbacks

          @buffer: Buffer
          @options: Options

          def close: () -> void
          def consume: (*untyped) -> void
          def empty: () -> bool
          def <<: (string) -> void

          private

          def initialize: (Buffer buffer, Options options) -> untyped
        end

        module Packet
          def self?.connect: (Parameters, uri) -> String
        end
      end
    end
  end
end
