module HTTPX
  module Plugins
    module Proxy
      module SSH
        def self.load_dependencies: (singleton(Session)) -> void

        module InstanceMethods
          private

          def build_gateway_socket: (int, URI::HTTP | URI::HTTPS, Options) ->  _ToIO
        end
      end
    end


    type sessionSSHProxy = Proxy::InstanceMethods & Proxy::SSH::InstanceMethods
  end
end
