module HTTPX
  module Transcoder
    module Body
      class Error < HTTPX::Error
      end

      class Encoder
        extend Forwardable

        include _Encoder
        include _ToS

        @raw: bodyIO

        def content_type: () -> String

        private

        def initialize: (untyped body) -> untyped
      end

      def self?.encode: (bodyIO body) -> Encoder
    end
  end
end