module HTTPX::Transcoder
  module Chunker
    CRLF: String

    class Error < HTTPX::Error
    end

    def self?.encode: (_Each[String] chunks) -> Encoder

    class Encoder
      @raw: _Each[String]

      include _Each[String]

      private

      def initialize: (_Each[String] chunks) -> untyped
    end

    class Decoder
      extend Forwardable
      include _ToS
      include _Each[String]

      def finished?: () -> bool
      def empty?: () -> bool
      def <<: (string) -> void
      def clear: () -> void

      private

      def initialize: (String, bool) -> untyped
                    | (String) -> untyped

      def nextstate: (Symbol) -> void
    end
  end
end
