module HTTPX
  module Transcoder
    module Deflate
      def self?.encode: (_Encoder body) -> Deflater
      def self?.decode: (Response body, ?bytesize: Integer) -> Inflater

      class Deflater < Transcoder::Deflater
        @deflater: Zlib::Deflate
      end

      class Inflater < Transcoder::Inflater
      end
    end
  end
end
