module HTTPX::Transcoder
  type urlencoded_input = Enumerable[[string, string], untyped]

  module Form
    def self?.encode: (urlencoded_input form) -> Encoder

    class Encoder
      include _Encoder
      include _ToS
      include _ToStr

      def content_type: () -> String

      private

      def initalize: (urlencoded_input form) -> untyped
    end
  end
end
