module HTTPX::Transcoder
  module JSON
    def self?.encode: (_ToJson json) -> Encoder

    class Encoder
      include _Encoder
      include _ToS
      include _ToStr

      def content_type: () -> String

      private

      def initalize: (_ToJson json) -> untyped
    end
  end
end
