module HTTPX::Transcoder
  module JSON
    def self?.encode: (_ToJson json) -> Encoder

    class Encoder
      extend Forwardable
      include _Encoder
      include _ToS

      def content_type: () -> String

      private

      def initialize: (_ToJson json) -> untyped
    end
  end
end
