module HTTPX
  module Plugins
    module Authentication
      class Basic
        @user: String
        @password: String

        def can_authenticate?: (String? authenticate) -> boolish

        def authenticate: (*untyped) -> String

        private

        def initialize: (string user, string password, *untyped) -> void

      end
    end
  end
end
