module HTTPX
  module Plugins
    module Authentication
      class Digest
        Error: singleton(HTTPX::Error)

        @user: String
        @password: String
        @hashed: bool

        def can_authenticate?: (String? authenticate) -> boolish

        def authenticate: (Request request, String authenticate) -> String

        private

        def generate_header: (String meth, String uri, String authenticate) -> String

        def initialize: (string user, string password, ?hashed: bool, **untyped) -> void

        def make_cnonce: () -> String

        def next_nonce: () -> Integer

        def raise_format_error: () -> void
      end
    end
  end
end
