module HTTPX
  IPRegex: Regexp

  @ctx: OpenSSL::SSL::SSLContext
  @verify_hostname: bool

  class TLSError < OpenSSL::SSL::SSLError
  end

  class SSL < TCP
    TLS_OPTIONS: Hash[Symbol, untyped]

    def can_verify_peer?: () -> bool

    def verify_hostname: (String host) -> bool

    # :nocov:
    def try_ssl_connect: () -> void
  end
end
