module HTTPX
  class UDP
    include Loggable

    @host: String
    @port: Integer
    @io: UDPSocket
    @options: Options

    def initialize: (String ip, Integer port, Options options) -> void

    def to_io: () -> IO

    def connect: () -> void

    def connected?: () -> bool

    # :nocov:
    def close: () -> void

    def read: (Integer size, String buffer) -> Integer?

    def write: (Buffer buffer) -> Integer?
  end
end
