title: HTTPX 
description: A client library for making HTTP requests from Ruby.
baseurl: ""
url: honeyryderchuck.gitlab.io/httpx
markdown: kramdown
destination: build
gems:
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      type: pages
    values:
      layout: default
