title: HTTPX 
description: A client library for making HTTP requests from Ruby.
authorurl: https://gitlab.com/honeyryderchuck
repourl: https://gitlab.com/honeyryderchuck/httpx
baseurl: "/httpx"
url: honeyryderchuck.gitlab.io
markdown: kramdown
destination: build
github:
  repo: https://gitlab.com/honeyryderchuck/httpx

pagination:
  enabled: true
  debug: true
  per_page: 5
  sort_reverse: true

include:
  - wiki
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-gzip
  - jekyll-brotli
  - jekyll-paginate-v2