title: HTTPX 
description: A client library for making HTTP requests from Ruby.
baseurl: "/httpx"
url: honeyryderchuck.gitlab.io
markdown: kramdown
destination: build
plugins:
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      type: pages
    values:
      layout: default
