module HTTPX
  class Request::Body
    attr_reader options: Options

    @headers: Headers
    @body: body_encoder?
    @unbounded_body: bool

    def initialize: (Headers h, Options options, **untyped) -> void

    def each: () { (String) -> void } -> void
            | () -> Enumerable[String]

    def rewind: () -> void

    def empty?: () -> bool

    def bytesize: () -> (Integer | Float)

    def stream: (Transcoder::_Encoder) -> bodyIO

    def unbounded_body?: () -> bool

    def chunked?: () -> bool

    def chunk!: () -> void

    private

    def self.initialize_body: (Hash[Symbol, untyped] params) -> body_encoder?

    def self.initialize_deflater_body: (body_encoder body, Encoding | String encoding) -> body_encoder
  end
end