module HTTPX
  interface _Callable
    def call: (*untyped) -> void
  end

  module Callbacks
    def on: (Symbol) { (*untyped) -> void } -> ^(*untyped) -> void
    def once: (Symbol) { (*untyped) -> void } -> ^(*untyped) -> void
    def emit: (Symbol, *untyped) -> void

    def callbacks_for?: (Symbol) -> boolish
    def callbacks: () -> Hash[Symbol, Array[_Callable]]
                  | (Symbol) -> Array[_Callable]
  end
end