module HTTPX
  class Error < StandardError
  end

  class UnsupportedSchemeError < Error
  end

  class ConnectionError < Error
  end

  class TimeoutError < Error
    attr_reader timeout: Numeric

    def to_connection_error: () -> ConnectTimeoutError
    private

    def initialize: (Numeric timeout, String message) -> untyped
  end

  class PoolTimeoutError < TimeoutError
    attr_reader origin: String

    def initialize: (String origin, Numeric timeout) -> void
  end

  class ConnectTimeoutError < TimeoutError
  end

  class SettingsTimeoutError < TimeoutError
  end

  class ResolveTimeoutError < TimeoutError
  end

  class RequestTimeoutError < TimeoutError
    attr_reader request: Request
    attr_reader response: response?

    def initialize: (Request request, response? response, Numeric timeout) -> void
  end

  class ReadTimeoutError < RequestTimeoutError
  end

  class WriteTimeoutError < RequestTimeoutError
  end

  class OperationTimeoutError < TimeoutError
  end

  class ResolveError < Error
  end

  class HTTPError < Error
    attr_reader response: Response

    private

    def initialize: (Response response) -> void
  end

  class NativeResolveError < ResolveError
    attr_reader connection: Connection
    attr_reader host: String

    private

    def initialize: (Connection connection, String hostname, ?String message) -> untyped
  end

  class MisdirectedRequestError < HTTPError
  end
end