module HTTPX
  extend Chainable

  EMPTY: Array[untyped]

  VERSION: String

  type uri = URI::HTTP | URI::HTTPS | string
  type generic_uri = String | URI::Generic

  type verb = :options | :get | :head | :post | :put | :delete | :trace | :connect |
              :propfind | :proppatch | :mkcol | :copy | :move | :lock | :unlock | :orderpatch |
              :acl | :report | :patch | :search

  module Plugins
    def self?.load_plugin: (Symbol) -> Module

    def self?.register_plugin: (Symbol, Module) -> void
  end
end