module HTTPX
  extend Chainable

  VERSION: String

  type uri = URI::HTTP | URI::HTTPS | string

  type verb = :options | :get | :head | :post | :put | :delete | :trace | :connect |
              :propfind | :proppatch | :mkcol | :copy | :move | :lock | :unlock | :orderpatch |
              :acl | :report | :patch | :search

  interface _ReadableStream
    def read: (?int length, ?string outbuf) -> String?
  end

  interface _WritableStream
    def write: (*_ToS arg0) -> Integer
  end

  interface _ToIO
    def to_io: () -> IO
  end

  module Plugins
  end
end