module HTTPX
  interface _IOLogger
    def <<: (string?) -> void
  end

  module Loggable
    COLORS: Hash[Symbol, Integer]

    def log: (?level: Integer?, ?color: Symbol?) { () -> String } -> void

    def log_exception: (Exception error, ?level: Integer, ?color: Symbol) -> void
  end
end