module HTTPX
  interface _IOLogger
    def <<: (string?) -> void
  end

  module Loggable
    def log: (?level: Integer, ?color: Symbol) { () -> String } -> void

    def log_exception: (StandardError, **untyped) -> void
  end
end