module HTTPX
  interface _IOLogger
    def <<: (string?) -> void
  end

  module Loggable
    USE_DEBUG_LOG: bool

    COLORS: Hash[Symbol, Integer]

    def log: (?level: Integer?, ?color: Symbol?, ?debug_level: Integer, ?debug: _IOLogger?) { () -> String } -> void

    def log_exception: (Exception error, ?level: Integer, ?color: Symbol, ?debug_level: Integer, ?debug: _IOLogger?) -> void

    def log_redact_headers: (_ToS text) -> String

    def log_redact_body: (_ToS text) -> String

    def log_redact: (_ToS text, bool should_redact) -> String
  end
end