module HTTPX::Registry[unchecked out T, unchecked out V]
  class Error < HTTPX::Error
  end

  # type registrable = Symbol | String | Class

  def self.registry: [T, V] (T) -> Class
                   | [T, V] () -> Hash[T, V]

  def self.register: [T, V] (T tag,  V handler) -> void

  def registry: (?T tag) -> V
end
