module HTTPX
  class Request
    extend Forwardable
    include Loggable
    include Callbacks

    METHODS: Array[Symbol]
    USER_AGENT: String

    attr_reader verb: verb
    attr_reader uri: http_uri
    attr_reader headers: Headers
    attr_reader body: Body
    attr_reader state: Symbol
    attr_reader options: Options
    attr_reader response: response?
    attr_reader drain_error: StandardError?
    attr_reader active_timeouts: Array[Symbol]

    attr_reader context: Fiber

    attr_accessor peer_address: ipaddr?

    attr_writer persistent: bool

    @ping: bool
    @query_params: Hash[interned, untyped]?
    @trailers: Headers?
    @informational_status: Integer?
    @query: String?
    @drainer: Enumerator[String, void]?

    def initialize: (Symbol | String verb, generic_uri uri, Options options, ?request_params params) -> untyped

    def set_context!: () -> void

    def current_context?: () -> bool

    def ping?: () -> bool

    def ping!: () -> void

    def empty?: () -> bool

    def close: () -> void

    def interests: () -> (:r | :w)

    def can_buffer? : () -> bool

    def merge_headers: (_Each[[String, headers_value]]) -> void

    def scheme: () -> String

    def response=: (response) -> void

    def path: () -> String

    def authority: () -> String

    def origin: () -> String

    def query: () -> String

    def drain_body: () -> String?

    def inspect: () -> String

    def transition: (Symbol) -> void

    def expects?: () -> boolish

    def trailers: () -> Headers

    def trailers?: () -> boolish

    def persistent?: () -> bool

    def read_timeout: () -> Numeric?

    def write_timeout: () -> Numeric?

    def request_timeout: () -> Numeric?

    def set_timeout_callback: (Symbol event) { (*untyped) -> void } -> void

    private

    def initialize_body: (Options options) -> Transcoder::_Encoder?

  end
end
