module HTTPX
  class Selector
    READABLE: Array[Symbol]
    WRITABLE: Array[Symbol]
    @selectables: Array[_ToIO]

    def register: (_ToIO) -> void
    def deregister: (_ToIO) -> void

    def select: (Numeric? interval) { (_ToIO) -> void } -> void

    private

    def initialize: () -> untyped

    def select_many: (Numeric? interval) { (_ToIO) -> void } -> void
    def select_one: (Numeric? interval) { (_ToIO) -> void } -> void
  end

  type io_interests = :r | :w | :rw
end