module HTTPX
  class Timeout
    CONNECT_TIMEOUT: Numeric
    KEEP_ALIVE_TIMEOUT: Numeric
    OPERATION_TIMEOUT: Numeric

    attr_reader connect_timeout: Numeric
    attr_reader operation_timeout: Numeric
    attr_reader total_timeout: Numeric?
    attr_reader keep_alive_timeout: Numeric?

    def self.new: (instance | Hash[Symbol, untyped]) -> instance
                | () -> instance

    def ==: (untyped other) -> bool 

    def merge: (Timeout | Hash[Symbol, untyped]) -> instance

    private

    def initialize: (
      ?connect_timeout: Numeric,
      ?operation_timeout: Numeric,
      ?keep_alive_timeout: Numeric,
      ?total_timeout: Numeric | nil,
      ?loop_timeout: Numeric | nil
    ) -> untyped
  end
end
