module HTTPX
  type bodyIO = _ReadableStream | _Each[String, untyped] | _ToS

  module Transcoder
    extend HTTPX::Registry[String, Class]

    interface _Encoder
      def bytesize: () -> Integer
    end

    interface _Decoder
      def decode: (string) -> String
    end
  end
end
