module HTTPX
  module Resolver
    module ResolverMixin
      include Callbacks
      include Loggable

      CHECK_IF_IP: ^(String name) -> bool

      def uncache: (Connection) -> void

      private

      def emit_addresses: (Connection, Array[ipaddr]) -> void

      def early_resolve: (Connection, ?hostname: String) -> void

      def ip_resolve: (String hostname) -> Array[ipaddr]?

      def system_resolve: (String hostname) -> Array[ipaddr]?

      def emit_resolve_error: (Connection, ?String hostname, ?StandardError) -> void

      def resolve_error: (String hostname, ?StandardError?) -> void
    end
  end
end
