module HTTPX
  module Resolver
    class Resolver
      include Loggable

      include _Selectable

      RECORD_TYPES: Hash[ip_family, singleton(Resolv::DNS::Resource)]

      FAMILY_TYPES: Hash[singleton(Resolv::DNS::Resource), String]

      attr_reader family: ip_family

      attr_reader options: Options

      attr_writer current_selector: Selector?

      attr_writer current_session: Session?

      attr_accessor multi: Multi?

      @record_type: singleton(Resolv::DNS::Resource)
      @resolver_options: Hash[Symbol, untyped]
      @connections: Array[Connection]

      def close: () -> void

      def force_close: (*untyped args) -> void

      def closed?: () -> bool

      def empty?: () -> bool

      def each_connection: () { (Connection connection) -> void } -> void

      def emit_addresses: (Connection connection, ip_family family, Array[ipaddr], ?bool early_resolve) -> void

      def handle_error: (ResolveError | StandardError) -> void

      def self.multi?: () -> bool

      def early_resolve: (Connection connection, ?hostname: String) -> bool

      private

      def resolve: (?Connection connection, ?String hostname) -> void

      def emit_resolved_connection: (Connection connection, Array[ipaddr] addresses, bool early_resolve) -> void

      def initialize: (ip_family family, Options options) -> void

      def resolve_connection: (Connection connection) -> void

      def emit_connection_error: (Connection connection, StandardError error) -> void

      def emit_resolve_error: (Connection connection, ?String hostname, ?StandardError) -> void

      def resolve_error: (String hostname, ?StandardError?) -> (ResolveError | ResolveTimeoutError)

      def close_or_resolve: () -> void
    end
  end
end
