module HTTPX
  module Resolver
    class System < Resolver
      RESOLV_ERRORS: Array[singleton(StandardError)] # ResolvError

      @resolver: Resolv::DNS

      def <<: (Connection) -> void
    end
  end
end