module HTTPX
  module Resolver
    class System
      include ResolverMixin

      RESOLV_ERRORS: Array[StandardError] # ResolvError

      def closed?: () -> true

      def empty?: () -> true

      def <<: (Connection) -> void

      private

      def initialize: (options) -> untyped
    end
  end
end