module HTTPX
  module Transcoder
    class BodyReader
      @body: Object & (_Reader | _Each[String])

      def initialize: (body_encoder body) -> void

      def bytesize: () -> (Integer | Float)

      def read: (?int? length, ?string? outbuf) -> String?

      def close: () -> void
    end
  end
end