module HTTPX
  module Transcoder
    class Deflater
      extend Forwardable

      @body: BodyReader
      @buffer: Response::Buffer?
      @body: _Encoder | StringIO

      attr_reader content_type: String

      def initialize: (_Encoder body) -> void

      def bytesize: () -> (Integer | Float)

      def read: (?int? length, ?string outbuf) -> String?

      def close: () -> void

      def deflate: (String? chunk) -> String?

      private

      def buffer_deflate!: () -> void

    end
  end
end
